/** 東京都区市町村（23区 + 多摩26市3町1村） */
export const TOKYO_MUNICIPALITIES = [
  // 23区
  { code: '131016', name: '千代田区', nameEn: 'chiyoda-ku' },
  { code: '131024', name: '中央区', nameEn: 'chuo-ku' },
  { code: '131032', name: '港区', nameEn: 'minato-ku' },
  { code: '131041', name: '新宿区', nameEn: 'shinjuku-ku' },
  { code: '131059', name: '文京区', nameEn: 'bunkyo-ku' },
  { code: '131067', name: '台東区', nameEn: 'taito-ku' },
  { code: '131075', name: '墨田区', nameEn: 'sumida-ku' },
  { code: '131083', name: '江東区', nameEn: 'koto-ku' },
  { code: '131091', name: '品川区', nameEn: 'shinagawa-ku' },
  { code: '131105', name: '目黒区', nameEn: 'meguro-ku' },
  { code: '131113', name: '大田区', nameEn: 'ota-ku' },
  { code: '131121', name: '世田谷区', nameEn: 'setagaya-ku' },
  { code: '131130', name: '渋谷区', nameEn: 'shibuya-ku' },
  { code: '131148', name: '中野区', nameEn: 'nakano-ku' },
  { code: '131156', name: '杉並区', nameEn: 'suginami-ku' },
  { code: '131164', name: '豊島区', nameEn: 'toshima-ku' },
  { code: '131172', name: '北区', nameEn: 'kita-ku' },
  { code: '131181', name: '荒川区', nameEn: 'arakawa-ku' },
  { code: '131199', name: '板橋区', nameEn: 'itabashi-ku' },
  { code: '131202', name: '練馬区', nameEn: 'nerima-ku' },
  { code: '131211', name: '足立区', nameEn: 'adachi-ku' },
  { code: '131229', name: '葛飾区', nameEn: 'katsushika-ku' },
  { code: '131237', name: '江戸川区', nameEn: 'edogawa-ku' },
  // 多摩地域 26市
  { code: '132012', name: '八王子市', nameEn: 'hachioji-shi' },
  { code: '132021', name: '立川市', nameEn: 'tachikawa-shi' },
  { code: '132039', name: '武蔵野市', nameEn: 'musashino-shi' },
  { code: '132047', name: '三鷹市', nameEn: 'mitaka-shi' },
  { code: '132055', name: '青梅市', nameEn: 'ome-shi' },
  { code: '132063', name: '府中市', nameEn: 'fuchu-shi' },
  { code: '132071', name: '昭島市', nameEn: 'akishima-shi' },
  { code: '132080', name: '調布市', nameEn: 'chofu-shi' },
  { code: '132098', name: '町田市', nameEn: 'machida-shi' },
  { code: '132101', name: '小金井市', nameEn: 'koganei-shi' },
  { code: '132110', name: '小平市', nameEn: 'kodaira-shi' },
  { code: '132128', name: '日野市', nameEn: 'hino-shi' },
  { code: '132136', name: '東村山市', nameEn: 'higashimurayama-shi' },
  { code: '132144', name: '国分寺市', nameEn: 'kokubunji-shi' },
  { code: '132152', name: '国立市', nameEn: 'kunitachi-shi' },
  { code: '132187', name: '福生市', nameEn: 'fussa-shi' },
  { code: '132195', name: '狛江市', nameEn: 'komae-shi' },
  { code: '132209', name: '東大和市', nameEn: 'higashiyamato-shi' },
  { code: '132217', name: '清瀬市', nameEn: 'kiyose-shi' },
  { code: '132225', name: '東久留米市', nameEn: 'higashikurume-shi' },
  { code: '132233', name: '武蔵村山市', nameEn: 'musashimurayama-shi' },
  { code: '132241', name: '多摩市', nameEn: 'tama-shi' },
  { code: '132250', name: '稲城市', nameEn: 'inagi-shi' },
  { code: '132276', name: '羽村市', nameEn: 'hamura-shi' },
  { code: '132284', name: 'あきる野市', nameEn: 'akiruno-shi' },
  { code: '132292', name: '西東京市', nameEn: 'nishitokyo-shi' },
  // 西多摩郡 3町1村
  { code: '133035', name: '瑞穂町', nameEn: 'mizuho-machi' },
  { code: '133051', name: '日の出町', nameEn: 'hinode-machi' },
  { code: '133078', name: '檜原村', nameEn: 'hinohara-mura' },
  { code: '133086', name: '奥多摩町', nameEn: 'okutama-machi' },
] as const;

/** 区市町村コードの型 */
export type MunicipalityCode = typeof TOKYO_MUNICIPALITIES[number]['code'];

/** 区市町村エントリの型 */
export type Municipality = typeof TOKYO_MUNICIPALITIES[number];
